# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dream architect
email: ray@zhaodao.ai
description: >
  白天造梦，夜晚做梦，偶尔盗梦
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://captainray.blog" # the base hostname & protocol for your site
paginate:	7 # The number of posts to show per page on your homepage

name: 'Ray'
bio: > 
  Put a ding in the universe.
author_image: "/assets/images/logo.jpg"
github_username:  tvvocold

# Google Analytics
analytics_id: "UA-47480129-15"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
