# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dream architect
email: tvvocold@gmail.com
description: >
  白天造梦，夜晚做梦，偶尔盗梦
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tvvocold.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Ray'
bio: > 
  To get what you want, you have to deserve what you want. 
  The world is not yet a crazy enough place to reward a whole bunch of undeserving people.
author_image: "/assets/images/logo.jpg"
github_username:  tvvocold

# Google Analytics
analytics_id: "UA-47480129-15"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
